import Head from "next/head";
import Layout from "../layout/Layout";

import { useRef } from "react";
import Image from "next/image";
import Eventnoire from "../components/eventnoire/Eventnoire";
import Register from "../components/register/Register";

export default function Home() {
  const updateRef = useRef();
  const partnerRef = useRef();

  return (
    <Layout ur={updateRef} pr={partnerRef}>
      <div>
        <Head>
          <title>Eventnoire</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/fav.svg" />
        </Head>

        {/* Navbar */}
        {/* eventnoire */}
        <Eventnoire ur={updateRef} pr={partnerRef} />
        {/* register */}
        <Register ur={updateRef} pr={partnerRef} />
        {/* footer */}
      </div>
    </Layout>
  );
}
