import Head from 'next/head'
import Image from 'next/image'
import Eventnoire from '../components/eventnoire/Eventnoire'
import Register from '../components/register/Register'
// import styles from '../styles/globals.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eventnoire experience</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      {/* eventnoire */}
      <Eventnoire />
      {/* register */}
      <Register />
      {/* footer */}
      
    </div>
  )
}
